### ISSUE TITLE
Docker + PHPStorm + d4m-nfs

### ISSUE THREAD

**Issue by anaelChardan** [IFSight/d4m-nfs#18]
Hi !

I try to setup Docker with PHPStorm 2016.3 in order to use XDebug properly but I have an issue and I think it's due to the sharing with d4m-nfs as the errors is

```
com.github.dockerjava.api.exception.DockerException: Mounts denied: /osxfs/#namespaces for more info.
.
nts/Workspace/Akeneo/PIM/1.6_ce_orm_php-5.6
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac

	at com.intellij.remoteServer.util.AgentTaskExecutor.execute(AgentTaskExecutor.java:29)
	at com.intellij.docker.remote.run.runtime.RemoteDockerRuntime.executeAgentTask(RemoteDockerRuntime.java:111)
	at com.intellij.docker.remote.run.runtime.RemoteDockerApplicationRuntime.executeAgentTask(RemoteDockerApplicationRuntime.java:162)
	at com.intellij.docker.remote.run.runtime.RemoteDockerApplicationRuntime.start(RemoteDockerApplicationRuntime.java:61)
	at com.intellij.docker.remote.run.runtime.RemoteDockerApplicationRuntime.startAndAttach(RemoteDockerApplicationRuntime.java:76)
	at com.intellij.docker.remote.run.runtime.RemoteDockerApplicationRuntime.startAndGetOutput(RemoteDockerApplicationRuntime.java:105)
	at com.jetbrains.php.remote.docker.PhpDockerRemoteProcessRunner.getProcessOutput(PhpDockerRemoteProcessRunner.java:70)
	... 16 more
```

But I can't see the full path PHPStorm tries to give to PHPStorm, could you have a look on it please ? Thanks !

**Comment by anaelChardan** [comment]
With the help of @Plopix, we arrived to connect docker to PHPStorm, you must use the same path on the mobyVM as your host path so use

```
/Users/{YOUR_USER}:/Users/{YOUR_USER}
```

In your config file.

Thanks.

**Comment by if-kenn** [comment]
Great that you figured it out.
